# This file defines the list of tools available on the CCU-AI-MCP server.

# For more information about the TOML format, see the official specification:
# https://toml.io/en/v1.1.0

# -----------------------------------------------------------------------------
[[tool]]
name = 'list_programs'
description = 'Lists all programs of the CCU. Active and visible flags are included.'
kind = 'hm-script'
enabled = true
script = '''
object eobj = dom.GetObject(ID_PROGRAMS);
if (eobj) {
	WriteLine("Result is a tab separated table with headers in the first line:");
	WriteLine("ISEID\tName\tDescription\tActive\tVisible");
	string id;
	integer count = 0;
	foreach (id, eobj.EnumIDs()) {
		object obj = dom.GetObject(id);
		WriteLine(obj.ID() # "\t" # obj.Name() # "\t" # obj.PrgInfo() # "\t" # obj.Active() # "\t" # obj.Visible());
		count = count + 1;
	}
	WriteLine("\nFound " # count # " programs.");
} else {
	WriteLine("ERROR: Object with ISEID ID_PROGRAMS not found.");
}
'''

# -----------------------------------------------------------------------------
[[tool]]
name = 'get_program'
description = 'Gets information about a CCU program. Currently only last execution time is returned.'
kind = 'hm-script'
enabled = true
script = '''
object pobj = dom.GetObject({{ .iseid }});
if (pobj && pobj.Type()==OT_PROGRAM) {
	WriteLine("Last execution time: " # pobj.ProgramLastExecuteTime());	
} else {
	WriteLine("ERROR: Object with ISEID {{ .iseid }} not found or is not a program.");
}
'''

[[tool.parameter]]
name = "iseid"
description = "ISEID of the program"
type = "string"

# -----------------------------------------------------------------------------
[[tool]]
name = 'execute_program'
description = 'Executes a program on the CCU.'
kind = 'hm-script'
enabled = false
script = '''
object pobj = dom.GetObject({{ .iseid }});
if (pobj && pobj.Type()==OT_PROGRAM) {
	pobj.ProgramExecute();
	WriteLine("Progam executed successfully on CCU.");
} else {
	WriteLine("ERROR: Object with ISEID {{ .iseid }} not found or is not a program.");
}

'''

[[tool.parameter]]
name = "iseid"
description = "ISEID of the program"
type = "string"
